name: Create Repository Visualization

on:
  push:
    branches:
      - main  # o il tuo branch principale
  workflow_dispatch:

# Aggiungi questa sezione
permissions:
  contents: write  # Questo è fondamentale per permettere la scrittura nel repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate Repository Visualization
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "diagram.svg"
          excluded_paths: "node_modules,dist,.github"
          commit_message: "Aggiornamento automatico del diagramma del repository"